# Generated by Django 4.1.5 on 2023-02-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='train_details',
            fields=[
                ('train_ID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('train_Name', models.CharField(max_length=260, unique=True)),
                ('origin_info', models.CharField(max_length=200)),
                ('destination_info', models.CharField(max_length=200)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
            ],
        ),
    ]
